//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.29 at 11:07:29 AM EET 
//


package own;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the own package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: own
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WriteMessageResponse }
     * 
     */
    public WriteMessageResponse createWriteMessageResponse() {
        return new WriteMessageResponse();
    }

    /**
     * Create an instance of {@link GetUsersResponse }
     * 
     */
    public GetUsersResponse createGetUsersResponse() {
        return new GetUsersResponse();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link ExitRequest }
     * 
     */
    public ExitRequest createExitRequest() {
        return new ExitRequest();
    }

    /**
     * Create an instance of {@link ReadOutboxRequest }
     * 
     */
    public ReadOutboxRequest createReadOutboxRequest() {
        return new ReadOutboxRequest();
    }

    /**
     * Create an instance of {@link ReadInfoResponse }
     * 
     */
    public ReadInfoResponse createReadInfoResponse() {
        return new ReadInfoResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link ReadInfoRequest }
     * 
     */
    public ReadInfoRequest createReadInfoRequest() {
        return new ReadInfoRequest();
    }

    /**
     * Create an instance of {@link GetUsersRequest }
     * 
     */
    public GetUsersRequest createGetUsersRequest() {
        return new GetUsersRequest();
    }

    /**
     * Create an instance of {@link DenemeResponse }
     * 
     */
    public DenemeResponse createDenemeResponse() {
        return new DenemeResponse();
    }

    /**
     * Create an instance of {@link ReadInboxRequest }
     * 
     */
    public ReadInboxRequest createReadInboxRequest() {
        return new ReadInboxRequest();
    }

    /**
     * Create an instance of {@link ReadResponse }
     * 
     */
    public ReadResponse createReadResponse() {
        return new ReadResponse();
    }

    /**
     * Create an instance of {@link MessageInfo }
     * 
     */
    public MessageInfo createMessageInfo() {
        return new MessageInfo();
    }

    /**
     * Create an instance of {@link DeleteUserRequest }
     * 
     */
    public DeleteUserRequest createDeleteUserRequest() {
        return new DeleteUserRequest();
    }

    /**
     * Create an instance of {@link CreateUserResponse }
     * 
     */
    public CreateUserResponse createCreateUserResponse() {
        return new CreateUserResponse();
    }

    /**
     * Create an instance of {@link WriteMessageRequest }
     * 
     */
    public WriteMessageRequest createWriteMessageRequest() {
        return new WriteMessageRequest();
    }

    /**
     * Create an instance of {@link DeleteUserResponse }
     * 
     */
    public DeleteUserResponse createDeleteUserResponse() {
        return new DeleteUserResponse();
    }

    /**
     * Create an instance of {@link CreateUserRequest }
     * 
     */
    public CreateUserRequest createCreateUserRequest() {
        return new CreateUserRequest();
    }

    /**
     * Create an instance of {@link DenemeRequest }
     * 
     */
    public DenemeRequest createDenemeRequest() {
        return new DenemeRequest();
    }

}
